/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminInviteRouteImport } from './routes/admin-invite'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminLeavesRouteImport } from './routes/admin.leaves'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentFinancialsRouteImport } from './routes/student.financials'
import { Route as StudentLeavesRouteImport } from './routes/student.leaves'
import { Route as StudentRequestsRouteImport } from './routes/student.requests'
import { Route as StudentRoomRouteImport } from './routes/student.room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/admin-invite',
  path: '/admin-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFinancialsRoute = StudentFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeavesRoute = StudentLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRequestsRoute = StudentRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRoomRoute = StudentRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-invite': typeof AdminInviteRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/financials': typeof StudentFinancialsRoute
  '/student/leaves': typeof StudentLeavesRoute
  '/student/requests': typeof StudentRequestsRoute
  '/student/room': typeof StudentRoomRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-invite': typeof AdminInviteRoute
  '/register': typeof RegisterRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/financials': typeof StudentFinancialsRoute
  '/student/leaves': typeof StudentLeavesRoute
  '/student/requests': typeof StudentRequestsRoute
  '/student/room': typeof StudentRoomRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-invite': typeof AdminInviteRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/financials': typeof StudentFinancialsRoute
  '/student/leaves': typeof StudentLeavesRoute
  '/student/requests': typeof StudentRequestsRoute
  '/student/room': typeof StudentRoomRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-invite'
    | '/register'
    | '/student'
    | '/admin/invoices'
    | '/admin/leaves'
    | '/admin/requests'
    | '/admin/rooms'
    | '/admin/staff'
    | '/admin/students'
    | '/student/financials'
    | '/student/leaves'
    | '/student/requests'
    | '/student/room'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-invite'
    | '/register'
    | '/admin/invoices'
    | '/admin/leaves'
    | '/admin/requests'
    | '/admin/rooms'
    | '/admin/staff'
    | '/admin/students'
    | '/student/financials'
    | '/student/leaves'
    | '/student/requests'
    | '/student/room'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-invite'
    | '/register'
    | '/student'
    | '/admin/invoices'
    | '/admin/leaves'
    | '/admin/requests'
    | '/admin/rooms'
    | '/admin/staff'
    | '/admin/students'
    | '/student/financials'
    | '/student/leaves'
    | '/student/requests'
    | '/student/room'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminInviteRoute: typeof AdminInviteRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-invite': {
      id: '/admin-invite'
      path: '/admin-invite'
      fullPath: '/admin-invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaves': {
      id: '/admin/leaves'
      path: '/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/financials': {
      id: '/student/financials'
      path: '/financials'
      fullPath: '/student/financials'
      preLoaderRoute: typeof StudentFinancialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaves': {
      id: '/student/leaves'
      path: '/leaves'
      fullPath: '/student/leaves'
      preLoaderRoute: typeof StudentLeavesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/requests': {
      id: '/student/requests'
      path: '/requests'
      fullPath: '/student/requests'
      preLoaderRoute: typeof StudentRequestsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/room': {
      id: '/student/room'
      path: '/room'
      fullPath: '/student/room'
      preLoaderRoute: typeof StudentRoomRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentFinancialsRoute: typeof StudentFinancialsRoute
  StudentLeavesRoute: typeof StudentLeavesRoute
  StudentRequestsRoute: typeof StudentRequestsRoute
  StudentRoomRoute: typeof StudentRoomRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentFinancialsRoute: StudentFinancialsRoute,
  StudentLeavesRoute: StudentLeavesRoute,
  StudentRequestsRoute: StudentRequestsRoute,
  StudentRoomRoute: StudentRoomRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminInviteRoute: AdminInviteRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
